name: test-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: a test step
      run: |
        python3 -c 'from something import collatz
                    print(collatz(2345))
                    print("Hello World")'
      shell: bash
      working-directory: src
