name: test-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: a test step
      run: |
        from something import collatz
        print(collatz(2345))
        print('Hello World')
      shell: python
      working-directory: ./src
